export const GET_TESTS = "GET_TESTS";
export const GET_TESTS_SUCCESS = "GET_TESTS_SUCCESS";
export const GET_TEST = "GET_TEST";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";
export const SUBMIT_ANSWERS = "SUBMIT_ANSWERS";
export const SUBMIT_ANSWERS_SUCCESS = "SUBMIT_ANSWERS_SUCCESS";
